In [22]:
# !pip install numpy

In [23]:
import numpy as np

In [24]:
arr = np.array([[1,2,3,4,5]])
print(arr)

[[1 2 3 4 5]]


In [25]:
type(arr)

numpy.ndarray

In [26]:
arr.ndim

2

In [27]:
arr.shape

(1, 5)

In [28]:
arr = np.array([[1,2,3,4,5]])
print(arr)
arr.dtype

[[1 2 3 4 5]]


dtype('int64')

In [29]:
arr_float = arr.astype('float')
arr_float

array([[1., 2., 3., 4., 5.]])

In [30]:
nums = np.array([1,4,8,9,12],dtype='float')
nums

array([ 1.,  4.,  8.,  9., 12.])

In [33]:
# num2 = np.array([1,2,3,4,5,6])
# num2.reshape(3,3) # rows ,columns

In [45]:
num3 = np.array([[1,2,3],[4,5,6]])

In [46]:
num3.ndim

2

In [50]:
num3

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.hsplit(num3,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [49]:
np.vsplit(num3,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [63]:
num4 = np.random.rand(3,4)

In [64]:
num5 = num4*200

num5

array([[176.13936511,  12.18297284, 100.7263949 ,  11.29992182],
       [132.43769972,  86.19643685,   7.91650555, 141.23406833],
       [ 97.89686167,  94.88148263,  79.16041396, 188.79726597]])